### ISSUE TITLE
error "source"

### ISSUE THREAD

**Issue by kalle07** [ayush-thakur02/xl-inpainting#1]
(system windwos) 

i run a lot of github pyton so i know a little  ;)

i cloned 
and installed and all is downloaded

but this error occurs:
"
(venv) d:\stable-A1111-inpaint\xl-inpainting>python inpaint.py
Loading pipeline components...:  57%|█████████████████████████████▋                      | 4/7 [00:00<00:00, 10.95it/s]The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 37000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00,  9.51it/s]
Traceback (most recent call last):
  File "d:\stable-A1111-inpaint\xl-inpainting\inpaint.py", line 75, in <module>
    image = gr.Image(source='upload', tool='sketch', elem_id="image_upload", type="pil", label="Upload",height=400)
  File "d:\stable-A1111-inpaint\xl-inpainting\venv\lib\site-packages\gradio\component_meta.py", line 146, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'source'!
"

**Comment by ayush-thakur02** [comment]
The source='upload' in line 75 seems to be causing the problem. There might be an issue with the image initialization, but I don't know why it works fine on Google Colab notebook.
I appreciate your feedback and I am working on solving this problem.

**Comment by kalle07** [comment]
i use none of them
i work with a1111 also 
(windows 10 with conda or pythen env )

**Comment by fengchenf** [comment]
the gradio libs don't match, maybe you need pip install -U gradio==3.27.0, that works.
